### ISSUE TITLE
message d'erreur CodeSandBox

### ISSUE THREAD

**Issue by anais2022** [MikeCodeur/react-prerequis-debutants#15]
Bonjour, J'essaye de récupérer le projet via codesandbox mais j'ai un message d'erreur concernant le container : "A sandbox error occurred, you can refresh the page to restart the container.". 
![IMG_0760](https://user-images.githubusercontent.com/112076305/195826753-8beb8eef-d337-4576-960b-4f705ab8abf9.jpg)

**Comment by MikeCodeur** [comment]
Merci de m'avoir remonté le problème. 

Codesandbox est optionnel, il est préférable de travailler sur ta machine.

N'arrives tu pas à lancer le projet de manière normal ?
