### ISSUE TITLE
Erreur: Validation de l environnement.

### ISSUE THREAD

**Issue by Wylenix** [MikeCodeur/react-prerequis-debutants#16]
Hello :)

Lors de l'installation du module de cours j'ai cette erreur lors du npm run init :: 

_Démarrage de l'installation de l' environnement...
Il y a des problèmes de compatibilité sur cet ordinateur:

    Version installé en local node@v20.9.0 actuellement, mais la version  node@12 || 14 || 15 || 16 est requis. Merci de mettre à jour node ici: https://nodejs.org ou installez NVM

Si vous souhaitez simplement ignorer cette erreur, vous pouvez installer les dépendances directement dans "/Users/lio/Documents/Programmation/TypeScript-MikeC/typescript-fondamentaux". Mais cela peut poser des problèmes par la suite...
    🚨  Erreur: Validation de l environnement. Merci de verifier les messages d' erreur et de résoudre les problèmes ._

Est-ce que ma version de node est trop récente ?

Merci par avance

**Comment by MikeCodeur** [comment]
Bonjour @Wylenix utilise Node Version 16.

Je te recommande d'utiliser nvm pour switcher plus facilement de version
