### ISSUE TITLE
Module Pre-requis HTML/CSS/JS - Fonctions - Exercice4

### ISSUE THREAD

**Issue by marialena31** [MikeCodeur/react-prerequis-debutants#5]
Bonjour,
sauf erreur de ma part, je crois qu'il y a une petite coquille : le calcul du périmètre dans l'énoncé serait plutôt d'utiliser les fonctions somme et multiplication. Et la correction donne la correction d'une fonction Aire et non Périmètre.

**Comment by MikeCodeur** [comment]
yes, c'est corrigé
