### ISSUE TITLE
npm run init error

### ISSUE THREAD

**Issue by Torres9-83** [MikeCodeur/react-prerequis-debutants#7]

**Comment by Torres9-83** [comment]
DWWM@OPTI-16 MINGW64 ~/Desktop/react-prerequis-debutants (master)
$ npm run init

> @mikecodeur/react-prerequis-debutants@1.0.0 init C:\Users\DWWM\Desktop\react-prerequis-debutants
> node install

▶️  Démarrage de l'installation de l' environnement...

npm ERR! code 1
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: line 22: .: git-sh-setup: file not found
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DWWM\AppData\Roaming\npm-cache\_logs\2021-11-16T12_28_39_135Z-debug.log
Install for [ 'git+https://gist.github.com/0eb1815df3e6ff119d776e44f23ee40c.git' ] failed with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @mikecodeur/react-prerequis-debutants@1.0.0 init: `node install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @mikecodeur/react-prerequis-debutants@1.0.0 init script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\DWWM\AppData\Roaming\npm-cache\_logs\2021-11-16T12_28_39_238Z-debug.log

**Comment by MikeCodeur** [comment]
Salut @Torres9-83 , as tu installé GIT pour windows correctement ?
