### ISSUE TITLE
Bug une fois dans la console

### ISSUE THREAD

**Issue by fabaformac** [MikeCodeur/react-prerequis-debutants#9]
Version de git, npm et node : ok
Git clone et install : ok
npm start : ok

Jusqu'à maintenant pas eu de soucis pour ouvrir les exos et les faire, mais là plus de résultats dans la console...à part des messages d'erreur :

GET ws://localhost:3000/sockjs-node [HTTP/1.1 101 Switching Protocols 1ms]
Erreur d’analyse de la valeur pour « -webkit-text-size-adjust ».  Déclaration abandonnée. 3:1:124
Erreur d’analyse de la valeur pour « animation ».  Déclaration abandonnée.

Du coup j'ai retenté un git clone mais j'ai toujours le même problème...

Help ! Merci :-)
Fab.

**Comment by fabaformac** [comment]
A priori le bug vient de firefox ! Ça fonctionne sur chrome...

**Comment by MikeCodeur** [comment]
Merci pour ton retour
